cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'ack'
brew 'elasticsearch'
brew 'grc'
brew 'hub'
brew 'hunspell'
brew 'imagemagick'
brew 'libpng'
brew 'mysql'
brew 'node'
brew 'openssl'
brew 'phantomjs'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'tig'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask 'android-studio'
cask 'bettertouchtool'
cask 'caffeine'
cask 'firefox'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'handbrake'
cask 'iterm2'
cask 'java'
cask 'licecap'
cask 'sequel-pro'
cask 'station'
cask 'steam'
cask 'sublime-text-dev'
cask 'the-unarchiver'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
